version: '3'
services:
  cam-backend:
    build: ./coargma-backend
    container_name: coargma-backend
    ports:
      - "15555:15555"
  coargma-demo:
    build: ./coargma-demo
    container_name: coargma_frontend
    ports:
      - "15556:15556"